- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: Add Java8 Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java8
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default