- name: Add the Jenkins key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key

- name: Add the Jenkins repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/

- name: Install Jenkins
  apt:
    update_cache: yes
    name: jenkins={{ jenkins_version }}

- name: Add docker group to jenkins
  shell: usermod -aG docker jenkins
