- name: add the Jenkins key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key

- name: add the Jenkins repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/

- name: Install Jenkins
  apt:
    update_cache: yes
    name: jenkins
