- name: apt-get install packages for docker
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Define lsb_release -cs.
  shell: lsb_release -cs
  ignore_errors: True
  register: lsb_release

- name: Add the docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable

- name: Install docker-ce.
  apt: name=docker-ce state=present update_cache=yes